[package]
name = "starkbid_contract"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.8.5"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.44.0" }

assert_macros = "2.8.5"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[tool.fmt]
sort-module-level-items = true
